### ISSUE TITLE
Nested sanitization

### ISSUE THREAD

**Issue by alanpearce** [paperhive/envfefe#32]
It would be nice to specify that a property is e.g. a JSON _object_ that should include a sanitised string e.g. `x: sanitize.string` etc.

According to @TorstenStueber, this should not be too hard.

**Comment by andrenarchy** [comment]
We could add functions like `validate.array()`, `validate.object()`, ... that you'd use like this:

```javascript
const config = parse({
  assets: value => validate.array(
    sanitize.json(value),
    item => validate.object(item, { code: validate.string, age: validate.number })
  )
})
```

I think it'd be quite easy to get this working such that config is of the type `{ assets: {code: string, age: number}[] }` automatically. Do you think this approach makes sense?

**Comment by andrenarchy** [comment]
This is now possible in combination with `fefe@^1.0.0` (make sure you use `envfefe@^2.0.0-beta.1`):
```typescript
import { parseEnv } from 'envfefe'
import { object, parseJson, string } from 'fefe'
import { pipe } from 'ramda'

const config = parseEnv({
  assets: pipe(parseJson(), object({ code: string() }))
})
```
